name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '24.8.0'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint, typecheck, and test with coverage
        run: npm run ci

      - name: Audit production dependencies (high severity)
        run: npm audit --omit=dev --audit-level=high

      - name: Build distribution artifact
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-explorer-dist
          path: dist
          retention-days: 7

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 3
