name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  NODE_VERSION: '24.8.0'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint, typecheck, and test with coverage
        run: npm run ci

      - name: Audit production dependencies (high severity)
        run: npm audit --omit=dev --audit-level=high

      - name: Build distribution artifact
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-explorer-dist
          path: dist
          retention-days: 7

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 3

  regtest-smoke:
    runs-on: ubuntu-latest
    needs: quality
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install bitcoind
        run: |
          BITCOIN_VERSION=27.1
          curl -fsSLO https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
          curl -fsSLO https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS
          grep "bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz" SHA256SUMS | sha256sum -c -
          tar -xzf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
          sudo install -m 0755 bitcoin-${BITCOIN_VERSION}/bin/bitcoind /usr/local/bin/
          sudo install -m 0755 bitcoin-${BITCOIN_VERSION}/bin/bitcoin-cli /usr/local/bin/

      - name: Install dependencies
        run: npm ci

      - name: Run regtest smoke tests
        env:
          BITCOIND_PATH: bitcoind
          REGTEST_SCRAPE_METRICS: 'true'
          REGTEST_ADDRESS_CHECK: 'true'
        run: npm run test:regtest

  benchmark-indexer:
    runs-on: ubuntu-latest
    needs: quality
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install bitcoind
        run: |
          BITCOIN_VERSION=27.1
          curl -fsSLO https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
          curl -fsSLO https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/SHA256SUMS
          grep "bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz" SHA256SUMS | sha256sum -c -
          tar -xzf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz
          sudo install -m 0755 bitcoin-${BITCOIN_VERSION}/bin/bitcoind /usr/local/bin/
          sudo install -m 0755 bitcoin-${BITCOIN_VERSION}/bin/bitcoin-cli /usr/local/bin/

      - name: Install dependencies
        run: npm ci

      - name: Run address indexer benchmark
        env:
          BITCOIND_PATH: bitcoind
          BENCH_MAX_INGEST_DELTA: '0.20'
          BENCH_MAX_SUMMARY_DELTA: '0.35'
          BENCH_MAX_TX_DELTA: '0.35'
          BENCH_MAX_UTXO_DELTA: '0.50'
        run: |
          npm run bench:address
          npm run bench:compare

      - name: Upload benchmark artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: address-indexer-benchmark
          path: bench/current-results.json
          retention-days: 7
